name: Print Pull Request Context
on: workflow_dispatch

jobs:
  print-pr-context:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR Context
        run: echo 'The PR number is ${{ toJSON(github) }}'
