name: Print Pull Request Context
#on: [workflow_dispatch, pull_request]
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened, closed]
jobs:
  print-pr-context:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR Context
        run: echo 'The PR number is ${{ toJSON(github.event) }}'







# Link where we can see all triggers such as opened, edited, reopened, closed, etc.
# https://docs:github:com/en/actions/using-workflows/events-that-trigger-workflows:
